name: CI
on:
  push:
    branches: [main, develop]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage
      - name: Run tests with coverage
        run: |
          pytest -q --cov --cov-report=xml:coverage.xml
      - name: Debug coverage files
        run: |
          pwd
          ls -lah
          sed -n '1,40p' coverage.xml | sed -n '1,5p'   # shows the header with paths
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          use_oidc: true
          verbose: true
          fail_ci_if_error: true
