name: CI
on:
  push:
    branches: [main, develop]      # runs on merge commits
  pull_request:           # runs on PRs
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # required for Codecov OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt pytest pytest-cov
      - run: pytest --cov=your_package --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          use_oidc: true
